server:
  port: 9001
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${local.host}:3306/hshop_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: ${local.host}
    port: 6379
    password: 110907
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    port: 465
    from: ${mail.from} # 发件人邮箱
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名
#  阿里云oss
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${aliyun.access.key.id}
    access-key-secret: ${aliyun.access.key.secret}
    bucket-name: harrison-shop