server:
  port: 9001
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://192.168.179.128:3306/hshop_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 192.168.179.128
    port: 6379
    password: 110907
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    port: 465
    from: 1109079622@qq.com # 发件人邮箱
    username: 1109079622@qq.com
    password: dddaefksrjphjegb
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名
#  阿里云oss
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tKUidLCppuh7o6Qi6qk
    access-key-secret: wd22VcdQrjzPJEmlfR1UeyM6iBi2bK
    bucket-name: harrison-shop